http.host: 0.0.0.0
xpack.monitoring.elasticsearch:
  hosts:
  - http://elasticsearch:9200
  password: your_password
  username: elastic
xpack.monitoring.elasticsearch.password: your_password
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.enabled: true
