version: "3.8"

networks:
  rafat97__network_public:
    name: rafat97__network_public
  rafat97__network_private:
    name: rafat97__network_private

services:
  web-server:
    image: nginx
    restart: always
    ports:
      - "3000:80"
      # - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - rafat97__network_private
      - rafat97__network_public

  test-service-1:
    image: rafat97/test-application:express-v1.0.0
    restart: always
    depends_on:
      - web-server
    networks:
      - rafat97__network_private

  test-service-2:
    image: rafat97/test-application:express-v1.0.0
    restart: always
    depends_on:
      - web-server
    networks:
      - rafat97__network_private

  test-service-3:
    image: rafat97/test-application:express-v1.0.0
    restart: always
    depends_on:
      - web-server
    networks:
      - rafat97__network_private

  test-service-4:
    image: rafat97/test-application:express-v1.0.0
    restart: always
    depends_on:
      - web-server
    networks:
      - rafat97__network_private

  test-service-5:
    image: rafat97/test-application:express-v1.0.0
    restart: always
    depends_on:
      - web-server
    networks:
      - rafat97__network_private
