version: "3.7"
services:

  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - mysql_db_data:/var/lib/mysql

volumes:
  mysql_db_data:
    # driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: './data'