version: "3.3"

volumes:
  db-vloume:

networks:
  my-network-dockerApp-database:

services:
  db-2:
    image: mysql:latest
    container_name: db-2
    restart: always
    environment:
      MYSQL_DATABASE: "exampledb-2"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "6606:3306"
    volumes:
      - db-vloume:/var/lib/mysql
    networks:
      - my-network-dockerApp-database

  db-management-2:
    depends_on:
      - db-2
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-2
    restart: always
    ports:
      - "6602:80"
    environment:
      PMA_HOST: db-2
    networks:
      - my-network-dockerApp-database
