version: '3.3'

volumes:
  db-vloume:

networks:
  my-network-dockerApp-database:

services:
  db:
      image: mysql:latest
      restart: always
      environment:
        MYSQL_DATABASE: "exampledb"
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        MYSQL_ROOT_PASSWORD: ""
      ports: 
        - '6605:3306'
      volumes:
        - db-vloume:/var/lib/mysql
      networks:
        - my-network-dockerApp-database

  db-management:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
        - "6601:80"
      environment:
        PMA_HOST: db
      networks:
        - my-network-dockerApp-database

