version: "3.8"

volumes:
  postgres_db_data:

networks:
  private_network__rafat97:
  public_network__rafat97:

services:
  postgres:
    image: postgres:14
    restart: always
    volumes:
      - ./postgres/docker-entrypoint-initdb.d/1-init-user-db.sh:/docker-entrypoint-initdb.d/1-init-user-db.sh
      - ./postgres/postgres.conf:/etc/postgresql/postgresql.conf
      - postgres_db_data:/var/lib/postgresql/data
    command: ["-c", "shared_buffers=512MB", "-c", "max_connections=10000"]
    networks:
      - private_network__rafat97
    environment:
      POSTGRES_DB: ${POSTGRES_ROOT_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_USER: ${POSTGRES_ROOT_USER}

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    ports:
      - 5050:80
    networks:
      - private_network__rafat97
      - public_network__rafat97
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

  server:
    image: postgrest/postgrest
    ports:
      - "8000:3000"
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_ROOT_USER}:${POSTGRES_ROOT_PASSWORD}@postgres:5432/${POSTGRES_ROOT_DATABASE}
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: ${POSTGRES_ROOT_USER} #In production this role should not be the same as the one used for the connection
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    networks:
      - private_network__rafat97
      - public_network__rafat97
    depends_on:
      - postgres

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - private_network__rafat97
      - public_network__rafat97
    environment:
      API_URL: http://localhost:8000/
