version: "3.7"

networks:
  private-openresty: 

services:
  openresty:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8083:443"
    networks:
      - private-openresty
    

  redis:
    image: redis/redis-stack:latest
    ports:
      - 6378:6379
      - 8001:8001
    networks:
      - private-openresty