version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - "xpack.security.enabled=false" 
      - xpack.security.http.ssl.enabled=false
      # - "ELASTIC_PASSWORD=your_password" # Set Elasticsearch password
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # - ELASTICSEARCH_USERNAME=kibana_system
      # - ELASTICSEARCH_PASSWORD=your_password
    ports:
      - "5601:5601"
    networks:
      - esnet
    depends_on:
      - elasticsearch

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:7.13.4
  #   container_name: logstash
  #   volumes:
  #     - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
  #     - ./logstash/pipeline:/usr/share/logstash/pipeline
  #   environment:
  #     - xpack.monitoring.elasticsearch.username=elastic  # Elasticsearch user
  #     - xpack.monitoring.elasticsearch.password=your_password  # Elasticsearch password
  #   ports:
  #     - "5044:5044"
  #     - "9600:9600"
  #   networks:
  #     - esnet
  #   depends_on:
  #     - elasticsearch

  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:7.13.4
  #   command: filebeat -e -strict.perms=false
  #   container_name: filebeat
  #   user: root
  #   volumes:
  #     - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
  #     - /var/log:/var/log:ro
  #   networks:
  #     - esnet
  #   depends_on:
  #     - logstash

volumes:
  esdata01:
    driver: local

networks:
  esnet:
    driver: bridge
