version: '3.8'

x-default-logging: &logging
  driver: 'json-file'
  options:
    max-size: '5m'
    max-file: '2'

volumes:
  postgresql_data:


networks:
  private_network:
    driver: bridge
    
  public_network:
    driver: bridge


services:
  postgres:
    image: supabase/postgres:15.1.0.117
    restart: always
    ports:
      - '5432:5432'
    networks:
      - private_network
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - log_min_messages=fatal # prevents Realtime polling queries from appearing in logs
    healthcheck:
      test: pg_isready -U postgres -h localhost
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - 'postgresql_data:/var/lib/postgresql'
    environment:
      PGPORT: 5432
      POSTGRES_PORT: 5432
      PGPASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DATABASE}
      POSTGRES_DB: ${POSTGRES_DATABASE}   
  
  pgbouncer:
    image: docker.io/bitnami/pgbouncer:1.21.0
    ports:
      - 6432
    networks:
      - private_network
    restart: always
    depends_on:
      - postgres
    environment:
       POSTGRESQL_HOST: postgres
       POSTGRESQL_USERNAME: ${POSTGRES_USER} 
       POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
       PGBOUNCER_DATABASE: "*"

  pgadmin:
    image: dpage/pgadmin4:7.8
    restart: always
    ports:
      - 5051:80
    networks:
      - private_network
      - public_network
    environment:
      PGADMIN_DEFAULT_EMAIL: 'test@mail.com'
      PGADMIN_DEFAULT_PASSWORD: '12345678'
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT: 'False'
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
      PGADMIN_CONFIG_PROXY_X_FOR_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_PROTO_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_PORT_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: "1"

  