
version: "3.3"

services:
  docker-in-docker-app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    restart: always

    # https://github.com/cruizba/ubuntu-dind/tree/master?tab=readme-ov-file
    # https://youtu.be/JyEwKm-OfxA?si=0LPrVdtcc7FiCHZV
    # runtime: sysbox-runc 