version: '3.7'

networks:
    dynamodb-local-network:


services:

    dynamodb-local:
        image:  amazon/dynamodb-local
        restart: always
        volumes:
          -  ./data:/home/dynamodblocal/data
        ports:
          - "8000:8000"
        command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
        networks:
           - dynamodb-local-network
        
    dynamodb-admin:
        image: aaronshaf/dynamodb-admin
        restart: always
        ports:
          - "8001:8001"
        environment:
          DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
          AWS_REGION: "us-west-2"
          AWS_ACCESS_KEY_ID: local
          AWS_SECRET_ACCESS_KEY: local
        depends_on:
          - dynamodb-local
        networks:
          - dynamodb-local-network
